import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';
import '../services/platform_services.dart';
import '../state/app_state.dart';

class MoreScreen extends ConsumerWidget { const MoreScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final s = ref.watch(settingsProvider); final d = ref.watch(dataProvider); return SafeArea(child: ListView(padding: const EdgeInsets.all(16), children: [const Text('More', style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold)), const SizedBox(height: 15), _item(context, Icons.bar_chart, 'Attendance & analytics', 'Rates, absence threshold warnings, study hours'), _item(context, Icons.repeat, 'Habit tracker', 'Daily, weekly and every-X-hours habits'), _item(context, Icons.timer, 'Focus & exam mode', 'Pomodoro study timer and exam countdowns'), const Divider(height: 32), const Text('Data & backup', style: TextStyle(fontWeight: FontWeight.bold)), ListTile(leading: const Icon(Icons.upload_file), title: const Text('Export JSON backup'), onTap: () => ExportService().shareBackup(d.subjects, d.events, d.tasks)), ListTile(leading: const Icon(Icons.download), title: const Text('Import JSON backup'), onTap: () async { final backup = await ExportService().importBackup(); if (backup != null) ref.read(dataProvider.notifier).restore(subjects: backup.subjects, events: backup.events, tasks: backup.tasks); }), const Divider(height: 32), const Text('Settings', style: TextStyle(fontWeight: FontWeight.bold)), SwitchListTile(value: s.motivationEnabled, onChanged: (v) => ref.read(settingsProvider.notifier).update(s.copyWith(motivationEnabled: v)), title: const Text('Private daily motivation'), subtitle: const Text('Delivered only in the system notification shade')), ListTile(leading: const Icon(Icons.language), title: const Text('Language'), trailing: DropdownButton<String>(value: s.locale.languageCode, items: const [DropdownMenuItem(value: 'en', child: Text('English')), DropdownMenuItem(value: 'ar', child: Text('العربية'))], onChanged: (v) { if (v != null) ref.read(settingsProvider.notifier).update(s.copyWith(locale: Locale(v))); })), ListTile(leading: const Icon(Icons.brightness_6), title: const Text('Theme'), trailing: DropdownButton<ThemeMode>(value: s.themeMode, items: const [DropdownMenuItem(value: ThemeMode.system, child: Text('System')), DropdownMenuItem(value: ThemeMode.light, child: Text('Light')), DropdownMenuItem(value: ThemeMode.dark, child: Text('Dark'))], onChanged: (v) { if (v != null) ref.read(settingsProvider.notifier).update(s.copyWith(themeMode: v)); })), SwitchListTile(value: s.autoMute, onChanged: (v) async { if (v) await NotificationService.instance.requestDndAccess(); ref.read(settingsProvider.notifier).update(s.copyWith(autoMute: v)); }, title: const Text('Auto-mute during classes'), subtitle: const Text('Requires Do Not Disturb access')), const Divider(height: 32), const Text('About', style: TextStyle(fontWeight: FontWeight.bold)), ListTile(title: const Text('Developed with 💻 by Ahmed Alaa'), subtitle: const Text('LinkedIn & GitHub'), onTap: () => _about(context))])); }
 Widget _item(BuildContext c, IconData i, String t, String st) => ListTile(leading: Icon(i), title: Text(t), subtitle: Text(st), trailing: const Icon(Icons.chevron_right), onTap: () {});
 void _about(BuildContext context) => showAboutDialog(context: context, applicationName: 'Unimate', applicationVersion: '1.0.0', children: [const Text('Student productivity and academic routine management.'), TextButton(onPressed: () => launchUrl(Uri.parse('https://www.linkedin.com/in/ahmed-alaa-897a633a8/'), mode: LaunchMode.externalApplication), child: const Text('LinkedIn')), TextButton(onPressed: () => launchUrl(Uri.parse('https://github.com/zaedvg3096432-droid'), mode: LaunchMode.externalApplication), child: const Text('GitHub'))]);
}

