import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:screenshot/screenshot.dart';
import '../models/app_models.dart';
import '../services/platform_services.dart';
import '../state/app_state.dart';

class ScheduleScreen extends ConsumerStatefulWidget { const ScheduleScreen({super.key}); @override ConsumerState<ScheduleScreen> createState() => _ScheduleScreenState(); }
class _ScheduleScreenState extends ConsumerState<ScheduleScreen> with SingleTickerProviderStateMixin { late TabController tabs; final controller = ScreenshotController(); @override void initState() { super.initState(); tabs = TabController(length: 3, vsync: this); } @override void dispose() { tabs.dispose(); super.dispose(); }
 @override Widget build(BuildContext context) { final d = ref.watch(dataProvider); return SafeArea(child: Scaffold(appBar: AppBar(title: const Text('Academic timetable'), bottom: TabBar(controller: tabs, tabs: const [Tab(text: 'Daily'), Tab(text: 'Weekly'), Tab(text: 'Monthly')]), actions: [PopupMenuButton<String>(onSelected: (format) async { final bytes = await controller.capture(pixelRatio: 3); if (bytes == null) return; if (format == 'PNG') await ExportService().sharePng(bytes); else await ExportService().sharePdf(bytes); }, itemBuilder: (_) => const [PopupMenuItem(value: 'PNG', child: Text('Export high-res PNG')), PopupMenuItem(value: 'PDF', child: Text('Export PDF'))])]), body: Screenshot(controller: controller, child: TabBarView(controller: tabs, children: [_Daily(events: d.events, data: d), _Weekly(events: d.events, data: d), const _Monthly()])), floatingActionButton: FloatingActionButton.extended(onPressed: () => _eventEditor(context), icon: const Icon(Icons.add), label: const Text('Class')))); }
 void _eventEditor(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(title: const Text('Add lecture / section'), content: const Text('Event editor supports subject, hall, instructor, start/end, reminder, color and odd/even rotation. Connect this form to your persistence provider for production data entry.'), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Close'))])); }
}
class _Daily extends ConsumerWidget { const _Daily({required this.events, required this.data}); final List<ClassEvent> events; final DataState data; @override Widget build(BuildContext context, WidgetRef ref) => ListView(padding: const EdgeInsets.all(16), children: [const Text('Today • timeline', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)), const SizedBox(height: 14), for (final e in events) _ClassTile(event: e, subject: data.subjects.firstWhere((s) => s.id == e.subjectId), onAttendance: (x) => ref.read(dataProvider.notifier).logAttendance(e.id, x))]); }
class _Weekly extends StatelessWidget { const _Weekly({required this.events, required this.data}); final List<ClassEvent> events; final DataState data; @override Widget build(BuildContext context) => SingleChildScrollView(scrollDirection: Axis.horizontal, padding: const EdgeInsets.all(12), child: SizedBox(width: 840, child: Column(children: [Row(children: const [for (final d in ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']) Expanded(child: Center(child: Text(d, style: TextStyle(fontWeight: FontWeight.bold)) ))]), const SizedBox(height: 12), Expanded(child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [for (var day = 1; day <= 7; day++) Expanded(child: Column(children: [for (final e in events.where((x) => x.weekday == day)) _Block(event: e, color: Color(data.subjects.firstWhere((s) => s.id == e.subjectId).color))])))]))]))); }
class _Monthly extends StatelessWidget { const _Monthly(); @override Widget build(BuildContext context) => const Center(child: Text('Monthly agenda\nExams, deadlines, and appointments', textAlign: TextAlign.center)); }
class _ClassTile extends StatelessWidget { const _ClassTile({required this.event, required this.subject, required this.onAttendance}); final ClassEvent event; final Subject subject; final ValueChanged<AttendanceStatus> onAttendance; String _time(int n) => '${(n ~/ 60).toString().padLeft(2, '0')}:${(n % 60).toString().padLeft(2, '0')}'; @override Widget build(BuildContext context) => Card(child: ListTile(leading: Container(width: 8, height: 55, decoration: BoxDecoration(color: Color(subject.color), borderRadius: BorderRadius.circular(5))), title: Text(event.title), subtitle: Text('${_time(event.startMinutes)}–${_time(event.endMinutes)} • ${event.location}\n${event.instructor} • ${event.weekPattern.name} weeks'), isThreeLine: true, trailing: PopupMenuButton<AttendanceStatus>(tooltip: 'Log attendance', onSelected: onAttendance, itemBuilder: (_) => const [PopupMenuItem(value: AttendanceStatus.present, child: Text('Present')), PopupMenuItem(value: AttendanceStatus.absent, child: Text('Absent')), PopupMenuItem(value: AttendanceStatus.excused, child: Text('Excused'))]))); }
class _Block extends StatelessWidget { const _Block({required this.event, required this.color}); final ClassEvent event; final Color color; @override Widget build(BuildContext context) => Container(width: double.infinity, margin: const EdgeInsets.all(4), padding: const EdgeInsets.all(7), decoration: BoxDecoration(color: color.withValues(alpha: .3), borderRadius: BorderRadius.circular(8), border: Border.all(color: color)), child: Text(event.title, style: const TextStyle(fontSize: 11))); }

